#PBS -N stmv.1.28.0
#PBS -l nodes=1:ppn=28
#PBS -l walltime=5:00:00
#PBS -S /bin/bash
#PBS -j oe
#
# 1 node, 28 ppn, no gpu
#
module load amber/16
#
job="1.28.0"
wrk=/fs/scratch/$USER/$PBS_JOBID
cd $PBS_O_WORKDIR
mkdir -p $wrk
cp mdin $wrk
bzcat < inpcrd.bz2 > $wrk/inpcrd
bzcat < prmtop.bz2 > $wrk/prmtop
cd $wrk
mpiexec pmemd.MPI -O -i mdin -o mdout.${job} -p prmtop -c inpcrd
cp mdout.${job} $PBS_O_WORKDIR
